{% set name = "monetdblite" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hannesmuehleisen/MonetDBLite-Python/archive/v{{ version }}.tar.gz
  sha256: 6941f1369f06cd80c5246ae59c0e865f126c15660f333506381af2ed7054762e

build:
  # skippping on win-py27 due to missing 'stdint.h' header: https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/21103611
  skip: True  # [win and py27]
  number: 1
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pytest-runner
    - python
    - setuptools        
  run:
    - pandas >=0.20
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - monetdblite

about:
  home: https://github.com/hannesmuehleisen/MonetDBLite-Python
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: 'MonetDBLite is a serverless SQL database that runs inside of your Python process and does not require the installation of any external software.'

  # The remaining entries in this section are optional, but recommended
  description: |
    MonetDBLite is a serverless SQL database that runs inside of your Python process and does not require
    the installation of any external software. MonetDBLite is based on free and open-source MonetDB,
    a product of the Centrum Wiskunde & Informatica.

extra:
  recipe-maintainers:
    - nicoddemus
