# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Uk31xYAk1g8tpwHD4RfdW/SDRT8ntJ/KdIll0Q6ZCVqUJlP7+Ju5nuq2bAemLcqBBlSt9UMezF7wb8MAv40Dpf2Ki02NcEgJXDqziY4rga6xTZVgOwiAN63Clb0xm4uZCIbovcdRVs53kmIo/yG6+FLf9Jaaafc4JhwigI/r5lpUxtwSEha/fK8+xJau1OcscaqU5jM2xn+rzN5BzOgehD+dLwOSyIxc2qOaKQTUqjDRL7J49MHDeOt+6L+JF0aL8QgiZHIw31twsR7whANdRru+D0kbPaQJ7JzySFP4hAt8Do2o5Yz6kQO9nDnYw3YHlwCkoThWmlajPOkQYRm10D5f+6Ity0KIKgBhjMUVQjB52prgZjaY7h2Y14ccpSlKVs9SEh9FDtSvkiNaiRAxOuZg2X+DBtkkHd3WOZdKj/uzMRCopuBMTZ6OKrJwEckQcy4KtZ3E1SH9wzv7TzFBn+EQLpD9X9dvvWuNAC6Ldam//H9vscinQpqEN04X9q2C+j0QszWlOAsuedctRDPVVwxY+DbUIPMeNur/AOhjgxiT33+D3ckfvGZ8eCAmzqakAalY3TWLcbtgZ11q5zEvruzTgpezeovKaLdhB3Jr9g23fqHbMWeKqYVxNjmdKilXq4V7KhUu1oHsOZmmgNNvkWa0ZFxkbfSwXZQBQEt2jLE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml