appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Uk31xYAk1g8tpwHD4RfdW/SDRT8ntJ/KdIll0Q6ZCVqUJlP7+Ju5nuq2bAemLcqBBlSt9UMezF7wb8MAv40Dpf2Ki02NcEgJXDqziY4rga6xTZVgOwiAN63Clb0xm4uZCIbovcdRVs53kmIo/yG6+FLf9Jaaafc4JhwigI/r5lpUxtwSEha/fK8+xJau1OcscaqU5jM2xn+rzN5BzOgehD+dLwOSyIxc2qOaKQTUqjDRL7J49MHDeOt+6L+JF0aL8QgiZHIw31twsR7whANdRru+D0kbPaQJ7JzySFP4hAt8Do2o5Yz6kQO9nDnYw3YHlwCkoThWmlajPOkQYRm10D5f+6Ity0KIKgBhjMUVQjB52prgZjaY7h2Y14ccpSlKVs9SEh9FDtSvkiNaiRAxOuZg2X+DBtkkHd3WOZdKj/uzMRCopuBMTZ6OKrJwEckQcy4KtZ3E1SH9wzv7TzFBn+EQLpD9X9dvvWuNAC6Ldam//H9vscinQpqEN04X9q2C+j0QszWlOAsuedctRDPVVwxY+DbUIPMeNur/AOhjgxiT33+D3ckfvGZ8eCAmzqakAalY3TWLcbtgZ11q5zEvruzTgpezeovKaLdhB3Jr9g23fqHbMWeKqYVxNjmdKilXq4V7KhUu1oHsOZmmgNNvkWa0ZFxkbfSwXZQBQEt2jLE=}
